@startuml
interface Controller
interface Parser
interface Executor
interface Listener
interface View

Controller <-left-> Parser
Controller -down-> Executor
Controller <-up-> Listener
Controller -right-> View

entity simulation1
entity simulation2
entity simulationN

Executor .down.> simulation1
Executor .down.> simulation2
Executor .down.> simulationN
@enduml